name: indigenousnutrition
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1"

dependencies:
  flutter:
    sdk: flutter
      # The following adds the Cupertino Icons font to your application.
      # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  http: ^1.2.1
  google_fonts: ^6.2.1
  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  # native_notify: ^0.0.15
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  responsive_framework: ^1.0.0
  #modal_progress_hud: ^0.1.3
  modal_progress_hud_nsn: ^0.5.1
  flutter_native_splash: ^2.1.1
  pdfx: ^2.3.0
  device_info_plus_web: any
  firebase_auth_web: any
  firebase_core_web: any
  flutter_web_plugins:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/appicon.png"
flutter:
  uses-material-design: true
  assets: 
      - assets/
      - assets/recipe.jpg
      - assets/cgcouncelingcards.pdf
      - assets/cgmanuals.pdf
fluttertoast: ^4.0.0

flutter_native_splash:
  color: "##f0fff0"
  image: assets/splash.png
  android: true
  ios: true